// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGV7AIh4xbRBWcS6FwrOhVDAFRk4W-xAs',
    appId: '1:406747409124:web:52bc9a8cbc3bff10bedaf1',
    messagingSenderId: '406747409124',
    projectId: 'gestorremoto',
    authDomain: 'gestorremoto.firebaseapp.com',
    databaseURL: 'https://gestorremoto-default-rtdb.firebaseio.com',
    storageBucket: 'gestorremoto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApbaUdpO6I6V9qi_EG78O7kE2C7Lha-GI',
    appId: '1:406747409124:android:6b89224659b01af9bedaf1',
    messagingSenderId: '406747409124',
    projectId: 'gestorremoto',
    databaseURL: 'https://gestorremoto-default-rtdb.firebaseio.com',
    storageBucket: 'gestorremoto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAH6zTLA6xmuft2mgOjrKze2IoqyvFBEE',
    appId: '1:406747409124:ios:aee60737cb81ce6dbedaf1',
    messagingSenderId: '406747409124',
    projectId: 'gestorremoto',
    databaseURL: 'https://gestorremoto-default-rtdb.firebaseio.com',
    storageBucket: 'gestorremoto.firebasestorage.app',
    iosBundleId: 'com.ideiatecnologia.GestorRemoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAH6zTLA6xmuft2mgOjrKze2IoqyvFBEE',
    appId: '1:406747409124:ios:aee60737cb81ce6dbedaf1',
    messagingSenderId: '406747409124',
    projectId: 'gestorremoto',
    databaseURL: 'https://gestorremoto-default-rtdb.firebaseio.com',
    storageBucket: 'gestorremoto.firebasestorage.app',
    iosBundleId: 'com.ideiatecnologia.GestorRemoto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGV7AIh4xbRBWcS6FwrOhVDAFRk4W-xAs',
    appId: '1:406747409124:web:ad88b83bc2b9976ebedaf1',
    messagingSenderId: '406747409124',
    projectId: 'gestorremoto',
    authDomain: 'gestorremoto.firebaseapp.com',
    databaseURL: 'https://gestorremoto-default-rtdb.firebaseio.com',
    storageBucket: 'gestorremoto.firebasestorage.app',
  );

}